
pipeline {
    agent any

    options {
        timeout(time: 10, unit: 'MINUTES')   // timeout, not timeouts
        disableConcurrentBuilds()
        
    }

    parameters {
        choice(
            name: 'ACTION',
            choices: ['apply', 'destroy'],
            description: 'Select Action'     // add colon
        )
    }

    stages {
        stage('init and plan') {
            steps {
                ansiColor('xterm')
                dir('00-vpc') {
                    withAWS(region: 'us-east-1', credentials: 'aws-credes') {
                        sh 'terraform init -reconfigure'
                        sh 'terraform plan'
                    }
                }
            }
        }

        
    }

    post {
        always {
            deleteDir()
        }
    }
}